<?php

declare(strict_types=1);

namespace Firol\Controllers;

use Firol\Auth\Csrf;
use Firol\Auth\Tenant;
use Firol\Db;
use Firol\Http\Request;
use Firol\Http\Response;
use Firol\Storage\Storage;

/**
 * Inspector profile = the data printed on every PDF protocol generated by
 * a given user under a given account. One row per (user_id, account_id);
 * a user belonging to multiple accounts can have a different signature
 * and certification per account (different employer / oprávnenie).
 *
 * The signature PNG is stored under backend/storage/signatures/ —
 * outside the docroot — and streamed back through an authenticated PHP
 * endpoint, never via a public URL.
 */
final class InspectorProfileController
{
    /** Hard cap on uploaded signature size (PNG, ~512 KB is plenty). */
    private const MAX_SIGNATURE_BYTES = 524288;

    public static function show(Request $req): void
    {
        $userId    = Tenant::currentUserId();
        $accountId = Tenant::currentAccountId();

        $row = self::loadOrCreate($userId, $accountId);
        Response::json(['profile' => self::shape($row, $userId, $accountId)]);
    }

    public static function update(Request $req): void
    {
        Csrf::require($req);
        $userId    = Tenant::currentUserId();
        $accountId = Tenant::currentAccountId();

        self::loadOrCreate($userId, $accountId);

        $certRphp   = $req->jsonString('cert_rphp');
        $certOprava = $req->jsonString('cert_oprava');
        $certGeneral = $req->jsonString('cert_general');
        $validFrom   = $req->jsonString('valid_from');
        $validTo     = $req->jsonString('valid_to');
        $isActiveRaw = $req->json()['is_active'] ?? null;

        if ($validFrom !== null && !preg_match('/^\d{4}-\d{2}-\d{2}$/', $validFrom)) {
            Response::error('Invalid valid_from (expected YYYY-MM-DD)', 422);
        }
        if ($validTo !== null && !preg_match('/^\d{4}-\d{2}-\d{2}$/', $validTo)) {
            Response::error('Invalid valid_to (expected YYYY-MM-DD)', 422);
        }
        if ($validFrom !== null && $validTo !== null && $validTo < $validFrom) {
            Response::error('valid_to must be on or after valid_from', 422);
        }

        $isActive = is_bool($isActiveRaw) ? ($isActiveRaw ? 1 : 0) : null;

        Db::pdo()->prepare(
            'UPDATE inspector_profiles
             SET    cert_rphp   = ?,
                    cert_oprava = ?,
                    cert_general = ?,
                    valid_from   = ?,
                    valid_to     = ?,
                    is_active    = COALESCE(?, is_active)
             WHERE  user_id = ? AND account_id = ?'
        )->execute([
            $certRphp,
            $certOprava,
            $certGeneral,
            $validFrom,
            $validTo,
            $isActive,
            $userId,
            $accountId,
        ]);

        $row = self::loadOrCreate($userId, $accountId);
        Response::json(['profile' => self::shape($row, $userId, $accountId)]);
    }

    public static function uploadSignature(Request $req): void
    {
        Csrf::require($req);
        $userId    = Tenant::currentUserId();
        $accountId = Tenant::currentAccountId();

        self::loadOrCreate($userId, $accountId);

        $file = $_FILES['signature'] ?? null;
        if (!is_array($file) || ($file['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_OK) {
            Response::error('No signature file uploaded', 422);
        }
        if (($file['size'] ?? 0) > self::MAX_SIGNATURE_BYTES) {
            Response::error('Signature too large (max 512 KB)', 422);
        }

        $tmp = (string) ($file['tmp_name'] ?? '');
        if ($tmp === '' || !is_uploaded_file($tmp)) {
            Response::error('Upload failed', 422);
        }

        // Real MIME sniff — never trust the browser-supplied type. We only
        // accept PNGs because mPDF embeds them losslessly and they support
        // transparency, which makes signatures look natural on the PDF.
        $finfo = finfo_open(FILEINFO_MIME_TYPE);
        $mime  = $finfo ? finfo_file($finfo, $tmp) : false;
        if ($finfo) {
            finfo_close($finfo);
        }
        if ($mime !== 'image/png') {
            Response::error('Signature must be a PNG image', 422);
        }

        $dest = Storage::signaturePath($accountId, $userId);
        Storage::ensureDir(dirname($dest));
        if (!move_uploaded_file($tmp, $dest)) {
            Response::error('Failed to store signature', 500);
        }

        Db::pdo()->prepare(
            'UPDATE inspector_profiles
             SET    signature_path = ?
             WHERE  user_id = ? AND account_id = ?'
        )->execute([Storage::signatureRelative($accountId, $userId), $userId, $accountId]);

        $row = self::loadOrCreate($userId, $accountId);
        Response::json(['profile' => self::shape($row, $userId, $accountId)]);
    }

    public static function downloadSignature(Request $req): void
    {
        $userId    = Tenant::currentUserId();
        $accountId = Tenant::currentAccountId();

        $row  = self::loadOrCreate($userId, $accountId);
        $path = Storage::signaturePath($accountId, $userId);

        if (empty($row['signature_path']) || !is_file($path)) {
            Response::error('No signature on file', 404);
        }

        // Stream the bytes directly; no Response helper because this isn't
        // JSON. Cache hint kept short so an updated signature is reflected
        // immediately in the Settings preview.
        header('Content-Type: image/png');
        header('Content-Length: ' . filesize($path));
        header('Cache-Control: private, max-age=30');
        readfile($path);
        exit;
    }

    /** @return array<string, mixed> */
    private static function loadOrCreate(int $userId, int $accountId): array
    {
        $stmt = Db::pdo()->prepare(
            'SELECT signature_path, cert_rphp, cert_oprava, cert_general, valid_from, valid_to, is_active
             FROM   inspector_profiles
             WHERE  user_id = ? AND account_id = ?'
        );
        $stmt->execute([$userId, $accountId]);
        $row = $stmt->fetch();
        if ($row) {
            return $row;
        }

        // First touch creates an empty profile so subsequent updates can
        // run as plain UPDATEs instead of UPSERTs.
        Db::pdo()->prepare(
            'INSERT INTO inspector_profiles (user_id, account_id) VALUES (?, ?)'
        )->execute([$userId, $accountId]);

        $stmt->execute([$userId, $accountId]);
        return $stmt->fetch() ?: [
            'signature_path' => null,
            'cert_rphp'      => null,
            'cert_oprava'    => null,
            'cert_general'   => null,
            'valid_from'     => null,
            'valid_to'       => null,
            'is_active'      => 1,
        ];
    }

    /**
     * @param array<string, mixed> $row
     * @return array<string, mixed>
     */
    private static function shape(array $row, int $userId, int $accountId): array
    {
        return [
            'user_id'       => $userId,
            'account_id'    => $accountId,
            'has_signature' => !empty($row['signature_path'])
                                && is_file(Storage::signaturePath($accountId, $userId)),
            'cert_rphp'     => $row['cert_rphp'] ?? null,
            'cert_oprava'   => $row['cert_oprava'] ?? null,
            'cert_general'  => $row['cert_general'] ?? null,
            'valid_from'    => $row['valid_from'] ?? null,
            'valid_to'      => $row['valid_to'] ?? null,
            'is_active'     => (int) ($row['is_active'] ?? 1) === 1,
        ];
    }
}
